plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.4'
    mappings 'net.fabricmc:yarn:1.21.4+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.14.22'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.0+1.21.4'
}

loom {
    refreshVersions = true
    refreshDeps = true
    ide {
        runDir = "run"
    }
}
